version: '3'



services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: schedule_production_django
    platform: linux/x86_64
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - 8086:5000
    labels:
      - traefik.http.routers.calendar.rule=Host(`calendar.codershq.ae`)
      - traefik.http.routers.calendar.tls=true
      - traefik.http.routers.calendar.tls.certresolver=lets-encrypt
      - traefik.port=8086
    networks:
      - chq-net
      - internal


  redis:
    image: redis:6

networks:
  chq-net:
    external: true
  internal:
    external: false