# Generated by Django 4.0.8 on 2022-11-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
