# Generated by Django 4.0.8 on 2022-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodel_is_approved_eventmodel_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='attendees',
            field=models.IntegerField(default=0, help_text='Number of expected attendees if the event is private', verbose_name='Number of Attendees'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='seating',
            field=models.CharField(choices=[('TH', 'Theatre'), ('CL', 'Classroom'), ('BO', 'Boardroom'), ('CA', 'Cabaret'), ('UT', 'U-Shaped (With Tables)'), ('UW', 'U-Shaped (Without Tables)')], default='TH', help_text='What style of seating are you looking for?', max_length=2, verbose_name='Seating arrangement'),
        ),
    ]
