# Generated by Django 4.0.8 on 2022-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmodel_attendees_eventmodel_seating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='attendees',
            field=models.IntegerField(blank=True, default=0, help_text='Number of expected attendees if the event is private', null=True, verbose_name='Number of Attendees'),
        ),
    ]
