# Generated by Django 4.0.8 on 2022-11-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventmodel_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_catering', models.BooleanField(default=False, help_text='Are you bringing your own catering company?', verbose_name='Request Catering Permit')),
                ('catering', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catering Company Name')),
                ('has_photography', models.BooleanField(default=False, help_text='Are you bringing your own photographer/videographer?', verbose_name='Request Photography Permit')),
                ('photography', models.CharField(blank=True, help_text="If the photographer is freelance please type 'Freelance'", max_length=100, null=True, verbose_name='Photography Company Name')),
                ('photography_number', models.IntegerField(default=0, verbose_name='Number of photographers')),
                ('equipment', models.TextField(blank=True, help_text='Photography equipment details', null=True)),
                ('has_external_setup', models.BooleanField(default=False, help_text='Are you bringing your own external setup (chairs, tables, etc)?', verbose_name='Request External Setup Permit')),
                ('setup_details', models.TextField(blank=True, help_text='External setup details (tables, chairs, etc)', null=True)),
                ('setup_datetime', models.DateTimeField(blank=True, help_text='External setup date and time', null=True, verbose_name='External Setup Arrival')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventmodel')),
            ],
        ),
    ]
