# Generated by Django 4.0.8 on 2022-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventmodel_gc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
